window.DEADLINES_LAST_VERIFIED = "September 30, 2026";

window.CONFERENCES = [
    // Machine Learning
    {
        "name": "ICLR 2026",
        "fullName": "International Conference on Learning Representations",
        "category": "Machine Learning",
        "deadline": "2025-09-25T11:59:00Z",
        "deadlineZone": "AoE (UTC-12)",
        "date": "April 23-27, 2026",
        "location": "Rio de Janeiro, Brazil",
        "venue": "Riocentro Convention and Event Center",
        "website": "https://iclr.cc/Conferences/2026",
        "note": "Full paper deadline: September 24, 2025, 11:59 PM AoE."
    },
    {
        "name": "ICML 2026",
        "fullName": "International Conference on Machine Learning",
        "category": "Machine Learning",
        "deadline": "2026-01-29T11:59:00Z",
        "deadlineZone": "AoE (UTC-12)",
        "date": "July 6-11, 2026",
        "location": "Seoul, South Korea",
        "venue": "COEX Convention & Exhibition Center",
        "website": "https://icml.cc/Conferences/2026/CallForPapers",
        "note": "Abstract deadline: January 23; full paper deadline: January 28, 2026, AoE."
    },
    {
        "name": "NeurIPS 2026",
        "fullName": "Conference on Neural Information Processing Systems",
        "category": "Machine Learning",
        "deadline": "2026-05-07T11:59:00Z",
        "deadlineZone": "AoE (UTC-12)",
        "date": "December 6-12, 2026",
        "location": "Sydney, Australia",
        "venue": "International Convention Centre Sydney",
        "website": "https://neurips.cc/Conferences/2026/Dates",
        "note": "Abstract deadline: May 4; full paper deadline: May 6, 2026, AoE."
    },
    {
        "name": "ICLR 2027",
        "fullName": "International Conference on Learning Representations",
        "category": "Machine Learning",
        "deadline": "2026-09-26T11:59:00Z",
        "deadlineZone": "AoE (UTC-12)",
        "date": "April 26-30, 2027",
        "location": "California, USA",
        "venue": "TBA",
        "website": "https://iclr.cc/Conferences/2027/CallForPapers",
        "note": "Abstract deadline: September 18; full paper deadline: September 25, 2026, AoE."
    },
    {
        "name": "ICML 2027",
        "fullName": "International Conference on Machine Learning",
        "category": "Machine Learning",
        "deadline": "2027-01-29T11:59:00Z",
        "deadlineZone": "AoE estimate",
        "deadlineDateLabel": "January 28, 2027",
        "estimated": true,
        "date": "2027 (dates TBA)",
        "location": "South America",
        "venue": "TBA",
        "website": "https://icml.cc/Conferences/FutureMeetings",
        "note": "Estimated from recent ICML submission cycles; only the 2027 region is currently official."
    },
    {
        "name": "NeurIPS 2027",
        "fullName": "Conference on Neural Information Processing Systems",
        "category": "Machine Learning",
        "deadline": "2027-05-20T11:59:00Z",
        "deadlineZone": "AoE estimate",
        "deadlineDateLabel": "May 19, 2027",
        "estimated": true,
        "date": "2027 (dates TBA)",
        "location": "Europe",
        "venue": "TBA",
        "website": "https://neurips.cc/Conferences/FutureMeetings",
        "note": "Estimated from recent NeurIPS submission cycles; only Europe is currently official."
    },

    // Computer Vision
    {
        "name": "ICCV 2025",
        "fullName": "IEEE/CVF International Conference on Computer Vision",
        "category": "Computer Vision",
        "deadline": "2025-03-08T09:59:00Z",
        "deadlineZone": "HST (UTC-10)",
        "date": "October 19-23, 2025",
        "location": "Honolulu, Hawaii, USA",
        "venue": "Hawaii Convention Center",
        "website": "https://iccv.thecvf.com/Conferences/2025/CallForPapers",
        "note": "Paper and supplementary-material deadline: March 7, 2025, 11:59 PM HST."
    },
    {
        "name": "CVPR 2026",
        "fullName": "IEEE/CVF Conference on Computer Vision and Pattern Recognition",
        "category": "Computer Vision",
        "deadline": "2025-11-14T11:59:00Z",
        "deadlineZone": "AoE (UTC-12)",
        "date": "June 3-7, 2026",
        "location": "Denver, Colorado, USA",
        "venue": "Colorado Convention Center",
        "website": "https://cvpr.thecvf.com/Conferences/2026/CallForPapers",
        "note": "Paper registration: November 7; full paper deadline: November 13, 2025, AoE."
    },
    {
        "name": "ECCV 2026",
        "fullName": "European Conference on Computer Vision",
        "category": "Computer Vision",
        "deadline": "2026-03-05T22:00:00Z",
        "deadlineZone": "CET (UTC+1)",
        "date": "September 8-13, 2026",
        "location": "Malmö, Sweden",
        "venue": "Malmö Arena and Malmömässan",
        "website": "https://eccv.ecva.net/Conferences/2026",
        "note": "Paper registration: February 26; full paper deadline: March 5, 2026, 11:00 PM CET."
    },
    {
        "name": "CVPR 2027",
        "fullName": "IEEE/CVF Conference on Computer Vision and Pattern Recognition",
        "category": "Computer Vision",
        "deadline": "2026-11-17T11:59:00Z",
        "deadlineZone": "AoE (UTC-12)",
        "date": "June 20-25, 2027",
        "location": "Seattle, Washington, USA",
        "venue": "Seattle Convention Center",
        "website": "https://cvpr.thecvf.com/Conferences/2027/CallForPapers",
        "note": "Paper registration: November 10; full paper deadline: November 16, 2026, AoE. No extension."
    },
    {
        "name": "ICCV 2027",
        "fullName": "IEEE/CVF International Conference on Computer Vision",
        "category": "Computer Vision",
        "deadline": "2027-03-06T11:59:00Z",
        "deadlineZone": "AoE estimate",
        "deadlineDateLabel": "March 5, 2027",
        "estimated": true,
        "date": "October 2-8, 2027",
        "location": "Hong Kong",
        "venue": "TBA",
        "website": "https://www.thecvf.com/?p=137",
        "note": "Deadline estimated from recent ICCV cycles; the conference dates and Hong Kong location are official."
    },

    // Robot Learning / Robotics
    {
        "name": "ICRA 2026",
        "fullName": "IEEE International Conference on Robotics and Automation",
        "category": "Robot Learning",
        "deadline": "2025-09-16T07:59:00Z",
        "deadlineZone": "PST (UTC-8)",
        "date": "June 1-5, 2026",
        "location": "Vienna, Austria",
        "venue": "Messe Wien",
        "website": "https://2026.ieee-icra.org/",
        "note": "Full paper deadline: September 15, 2025, 11:59 PM PST."
    },
    {
        "name": "RSS 2026",
        "fullName": "Robotics: Science and Systems",
        "category": "Robot Learning",
        "deadline": "2026-01-31T11:59:00Z",
        "deadlineZone": "AoE (UTC-12)",
        "date": "July 13-17, 2026",
        "location": "Sydney, Australia",
        "venue": "University of Technology Sydney",
        "website": "https://roboticsconference.org/2026/",
        "note": "Title deadline: January 23; full paper deadline: January 30, 2026, AoE."
    },
    {
        "name": "IROS 2026",
        "fullName": "IEEE/RSJ International Conference on Intelligent Robots and Systems",
        "category": "Robot Learning",
        "deadline": "2026-03-03T07:59:00Z",
        "deadlineZone": "PST (UTC-8)",
        "date": "September 27-October 1, 2026",
        "location": "Pittsburgh, Pennsylvania, USA",
        "venue": "David L. Lawrence Convention Center",
        "website": "https://2026.ieee-iros.org/",
        "note": "Full paper deadline: March 2, 2026, 11:59 PM Pacific Time."
    },
    {
        "name": "CoRL 2026",
        "fullName": "Conference on Robot Learning",
        "category": "Robot Learning",
        "deadline": "2026-05-29T11:59:00Z",
        "deadlineZone": "AoE (UTC-12)",
        "date": "November 9-12, 2026",
        "location": "Austin, Texas, USA",
        "venue": "JW Marriott Austin, Hilton Austin, and Bass Concert Hall",
        "website": "https://2026.corl.org/contributions/instruction-for-authors",
        "note": "Abstract deadline: May 25; full paper deadline: May 28, 2026, AoE."
    },
    {
        "name": "Humanoids 2026",
        "fullName": "IEEE-RAS International Conference on Humanoid Robots",
        "category": "Robot Learning",
        "deadline": "2026-07-28T06:59:00Z",
        "deadlineZone": "PDT (UTC-7)",
        "date": "December 6-9, 2026",
        "location": "Santa Clara, California, USA",
        "venue": "TBA",
        "website": "https://2026.ieee-humanoids.org/call-for-papers/",
        "note": "The final paper deadline was July 27, 2026, 11:59 PM Pacific Time."
    },
    {
        "name": "ICRA 2027",
        "fullName": "IEEE International Conference on Robotics and Automation",
        "category": "Robot Learning",
        "deadline": "2026-09-16T07:59:00Z",
        "deadlineZone": "PST (UTC-8)",
        "date": "May 24-28, 2027",
        "location": "Seoul, South Korea",
        "venue": "COEX Convention & Exhibition Center",
        "website": "https://2027.ieee-icra.org/contribute/call-for-icra-2027-papers-now-accepting-submissions/",
        "note": "Full paper deadline: September 15, 2026, 11:59 PM PST. The official CFP says no extension is planned."
    },
    {
        "name": "IROS 2027",
        "fullName": "IEEE/RSJ International Conference on Intelligent Robots and Systems",
        "category": "Robot Learning",
        "deadline": "2027-03-02T07:59:00Z",
        "deadlineZone": "Pacific Time estimate",
        "deadlineDateLabel": "March 1, 2027",
        "estimated": true,
        "date": "September 26-October 1, 2027",
        "location": "Florence, Italy",
        "venue": "Fortezza da Basso",
        "website": "https://www.ieee-ras.org/event/2027-ieee-rsj-international-conference-on-intelligent-robots-and-systems-iros-70525/",
        "note": "March 1 is official; the countdown assumes an end-of-day Pacific Time cutoff."
    },
    {
        "name": "RSS 2027",
        "fullName": "Robotics: Science and Systems",
        "category": "Robot Learning",
        "deadline": "2026-12-05T11:59:00Z",
        "deadlineZone": "AoE (UTC-12)",
        "date": "July 6-11, 2027",
        "location": "Athens, Greece",
        "venue": "TBA",
        "website": "https://roboticsconference.org/information/cfp/",
        "note": "Stage 1 extended abstract deadline: December 4, 2026; invited Stage 2 final paper deadline: April 16, 2027, AoE."
    },
    {
        "name": "CoRL 2027",
        "fullName": "Conference on Robot Learning",
        "category": "Robot Learning",
        "deadline": "2027-05-28T11:59:00Z",
        "deadlineZone": "AoE estimate",
        "deadlineDateLabel": "May 27, 2027",
        "estimated": true,
        "date": "TBA",
        "location": "TBA",
        "venue": "TBA",
        "website": "https://www.corl.org/",
        "note": "Deadline estimated from recent CoRL cycles; the 2027 CFP, dates, and location are not yet official."
    },
    {
        "name": "RA-L",
        "fullName": "IEEE Robotics and Automation Letters",
        "category": "Robot Learning",
        "deadline": null,
        "deadlineText": "Rolling submissions",
        "deadlineKind": "rolling",
        "date": "Open throughout the year",
        "location": "Journal",
        "venue": "IEEE Xplore",
        "website": "https://www.ieee-ras.org/publications/ieee-robotics-and-automation-letters/",
        "note": "RA-L has no conference-specific submission deadline. Accepted papers may be transferred for presentation at eligible RAS conferences."
    }
];
